#include "amtari.h"
#include <string.h>
#define MU_KEYBD 0x0001u
#define MU_BUTTON 0x0002u
#define MU_M1 0x0004u
#define MU_M2 0x0008u
#define MU_MESAG 0x0010u
#define MU_TIMER 0x0020u
int amtari_vdi_bind(struct amtari_context *c,amtari_vdi_dispatch_fn f,void*o){if(!c||!c->initialized)return AMTARI_EINVAL;c->vdi.dispatch=f;c->vdi.opaque=o;return 0;}int amtari_vdi_line_bind(struct amtari_context*c,amtari_vdi_line_fn f,void*o){if(!c||!c->initialized)return AMTARI_EINVAL;c->vdi.line=f;c->vdi.line_opaque=o;return 0;}int amtari_vdi_configure(struct amtari_context*c,uint16_t w,uint16_t h,uint16_t n){if(!c||!c->initialized||!w||!h||!n)return AMTARI_EINVAL;c->vdi.width=w;c->vdi.height=h;c->vdi.colors=n;if(!c->vdi.next_handle)c->vdi.next_handle=1;if(!c->vdi.line_style)c->vdi.line_style=1;return 0;}
static int32_t opnwk(struct amtari_context*c,int16_t*o,uint16_t oc,uint16_t*no,int16_t*p,uint16_t pc,uint16_t*np){uint16_t i;if(!c->vdi.width||!c->vdi.height||!c->vdi.colors)return AMTARI_ENOSYS;if(oc<45||pc<12||!o||!p)return AMTARI_EINVAL;for(i=0;i<45;i++)o[i]=0;for(i=0;i<12;i++)p[i]=0;o[0]=(int16_t)(c->vdi.width-1);o[1]=(int16_t)(c->vdi.height-1);o[3]=o[4]=o[5]=o[6]=o[7]=o[8]=o[9]=o[10]=1;o[13]=(int16_t)c->vdi.colors;o[35]=1;*no=45;*np=12;c->vdi.next_handle++;return 0;}static int32_t attr(struct amtari_context*c,uint16_t op,const int16_t*i,uint16_t n,int16_t*o,uint16_t cap,uint16_t*cnt){uint16_t v;if(!i||n<1||!o||cap<1)return AMTARI_EINVAL;v=(uint16_t)i[0];if(op==15){if(v<1||v>6)v=1;c->vdi.line_style=v;}else{if(v>=c->vdi.colors)v=1;c->vdi.line_color=v;}o[0]=(int16_t)v;*cnt=1;return 0;}static int32_t pline(struct amtari_context*c,const int16_t*p,uint16_t n){uint16_t i;if(!c->vdi.line)return AMTARI_ENOSYS;if(!p||n<4||(n&1))return AMTARI_EINVAL;for(i=0;i+3<n;i+=2)if(c->vdi.line(c->vdi.line_opaque,p[i],p[i+1],p[i+2],p[i+3],c->vdi.line_color,c->vdi.line_style))return AMTARI_EIO;return 0;}
int32_t amtari_vdi_dispatch(struct amtari_context*c,uint16_t op,const int16_t*i,uint16_t ni,const int16_t*p,uint16_t np,int16_t*o,uint16_t oc,uint16_t*no,int16_t*po,uint16_t pc,uint16_t*npo){int32_t r;if(!c||!c->initialized||!no||!npo)return AMTARI_EINVAL;*no=*npo=0;if(op==1)return opnwk(c,o,oc,no,po,pc,npo);if(op==6)return pline(c,p,np);if(op==15||op==17)return attr(c,op,i,ni,o,oc,no);if(!c->vdi.dispatch)return AMTARI_ENOSYS;r=c->vdi.dispatch(c->vdi.opaque,op,i,ni,p,np,o,oc,no,po,pc,npo);if(r)return r;if(*no>oc||*npo>pc)return AMTARI_EINVAL;return 0;}
int amtari_aes_bind(struct amtari_context*c,amtari_aes_dispatch_fn f,void*o){if(!c||!c->initialized)return AMTARI_EINVAL;c->aes.dispatch=f;c->aes.opaque=o;return 0;}int amtari_aes_timer_bind(struct amtari_context*c,amtari_aes_timer_fn f,void*o){if(!c||!c->initialized)return AMTARI_EINVAL;c->aes.timer=f;c->aes.timer_opaque=o;return 0;}int amtari_aes_mouse_bind(struct amtari_context*c,amtari_aes_mouse_fn f,void*o){if(!c||!c->initialized)return AMTARI_EINVAL;c->aes.mouse=f;c->aes.mouse_opaque=o;return 0;}int amtari_aes_cursor_bind(struct amtari_context*c,amtari_aes_cursor_fn f,void*o){if(!c||!c->initialized)return AMTARI_EINVAL;c->aes.cursor=f;c->aes.cursor_opaque=o;return 0;}int amtari_aes_set_application_name(struct amtari_context*c,const char*n){size_t z;if(!c||!c->initialized||!n)return AMTARI_EINVAL;z=strlen(n);if(!z||z>8)return AMTARI_EINVAL;memset(c->aes.application_name,0,9);memcpy(c->aes.application_name,n,z);return 0;}int amtari_aes_graf_configure(struct amtari_context*c,uint16_t h,uint16_t cw,uint16_t ch,uint16_t bw,uint16_t bh){if(!c||!c->initialized||!h||!cw||!ch||!bw||!bh)return AMTARI_EINVAL;c->aes.workstation_handle=h;c->aes.char_width=cw;c->aes.char_height=ch;c->aes.box_width=bw;c->aes.box_height=bh;return 0;}
static int32_t ainit(struct amtari_context*c,int16_t*o,uint16_t cap,uint16_t*n){uint16_t id;if(!o||cap<1)return AMTARI_EINVAL;if(c->aes.application_active)return AMTARI_EEXIST;if(!c->aes.next_application_id)c->aes.next_application_id=1;id=c->aes.next_application_id++;c->aes.current_application_id=id;c->aes.application_active=1;o[0]=(int16_t)id;*n=1;return 0;}static int32_t aexit(struct amtari_context*c,int16_t*o,uint16_t cap,uint16_t*n){if(!o||cap<1||!c->aes.application_active)return AMTARI_EINVAL;c->aes.application_active=0;c->aes.current_application_id=0;c->aes.message_pending=0;c->aes.message_length=0;o[0]=1;*n=1;return 0;}static int32_t afind(struct amtari_context*c,const uint32_t*a,uint16_t na,int16_t*o,uint16_t cap,uint16_t*n){char s[9];uint16_t i;uint32_t q;if(!o||cap<1||!a||na<1)return AMTARI_EINVAL;o[0]=-1;*n=1;if(!c->aes.application_active||!c->aes.application_name[0])return 0;q=a[0];for(i=0;i<8;i++){if(!amtari_guest_range_valid(c,q+i,1))return AMTARI_EFAULT;s[i]=(char)c->memory.data[q+i];if(!s[i])break;}if(i==8)s[8]=0;else s[i]=0;if(!strcmp(s,c->aes.application_name))o[0]=(int16_t)c->aes.current_application_id;return 0;}
static int32_t awrite(struct amtari_context*c,const int16_t*i,uint16_t ni,const uint32_t*a,uint16_t na,int16_t*o,uint16_t cap,uint16_t*n){uint16_t dest,len;uint32_t q;if(!o||cap<1||!i||ni<2||!a||na<1)return AMTARI_EINVAL;dest=(uint16_t)i[0];len=(uint16_t)i[1];q=a[0];o[0]=0;*n=1;if(!c->aes.application_active||dest!=c->aes.current_application_id||len>AMTARI_AES_MESSAGE_MAX||c->aes.message_pending)return 0;if(!amtari_guest_range_valid(c,q,len))return AMTARI_EFAULT;if(len)memcpy(c->aes.message,c->memory.data+q,len);c->aes.message_length=len;c->aes.message_destination=dest;c->aes.message_pending=1;o[0]=1;return 0;}
static int32_t aread(struct amtari_context*c,const int16_t*i,uint16_t ni,const uint32_t*a,uint16_t na,int16_t*o,uint16_t cap,uint16_t*n){uint16_t rid,len;uint32_t q;if(!o||cap<1||!i||ni<2||!a||na<1)return AMTARI_EINVAL;rid=(uint16_t)i[0];len=(uint16_t)i[1];q=a[0];o[0]=0;*n=1;if(!c->aes.application_active||rid!=c->aes.current_application_id||!c->aes.message_pending||c->aes.message_destination!=rid||len!=c->aes.message_length)return 0;if(!amtari_guest_range_valid(c,q,len))return AMTARI_EFAULT;if(len)memcpy(c->memory.data+q,c->aes.message,len);c->aes.message_pending=0;c->aes.message_length=0;c->aes.message_destination=0;o[0]=1;return 0;}
static int32_t emesag(struct amtari_context*c,const uint32_t*a,uint16_t na,int16_t*o,uint16_t cap,uint16_t*n){uint32_t q;if(!o||cap<1||!a||na<1)return AMTARI_EINVAL;q=a[0];o[0]=0;*n=1;if(!c->aes.application_active||!c->aes.message_pending||c->aes.message_destination!=c->aes.current_application_id||c->aes.message_length!=16)return 0;if(!amtari_guest_range_valid(c,q,16))return AMTARI_EFAULT;memcpy(c->memory.data+q,c->aes.message,16);c->aes.message_pending=0;c->aes.message_length=0;c->aes.message_destination=0;o[0]=1;return 0;}
static int32_t etimer(struct amtari_context*c,const int16_t*i,uint16_t ni,int16_t*o,uint16_t cap,uint16_t*n){uint32_t ms;if(!o||cap<1||!i||ni<2)return AMTARI_EINVAL;ms=(uint32_t)(uint16_t)i[0]|((uint32_t)(uint16_t)i[1]<<16);c->aes.last_timer_ms=ms;if(c->aes.timer&&c->aes.timer(c->aes.timer_opaque,ms))return AMTARI_EIO;o[0]=1;*n=1;return 0;}
static int32_t ekeybd(struct amtari_context*c,int16_t*o,uint16_t cap,uint16_t*n){int key;if(!o||cap<1)return AMTARI_EINVAL;o[0]=0;*n=1;if(!c->console.input_ready||!c->console.getc)return AMTARI_ENOSYS;if(c->console.input_ready(c->console.opaque)<=0)return 0;key=c->console.getc(c->console.opaque);if(key>=0)o[0]=(int16_t)(uint16_t)key;return 0;}
static int point_in_rect(int16_t x,int16_t y,int16_t rx,int16_t ry,int16_t rw,int16_t rh){int32_t px=x,py=y,left=rx,top=ry,right=left+rw,bottom=top+rh;return rw>0&&rh>0&&px>=left&&px<right&&py>=top&&py<bottom;}
static int32_t ebutton(struct amtari_context*c,const int16_t*i,uint16_t ni,int16_t*o,uint16_t cap,uint16_t*n){int16_t x=0,y=0;uint16_t buttons=0,kstate=0,clicks,mask,state;int ready;if(!i||ni<3||!o||cap<5)return AMTARI_EINVAL;memset(o,0,5*sizeof(*o));*n=5;if(!c->aes.mouse)return AMTARI_ENOSYS;ready=c->aes.mouse(c->aes.mouse_opaque,&x,&y,&buttons,&kstate);if(ready<=0)return 0;clicks=(uint16_t)i[0]&0x00ffu;mask=(uint16_t)i[1];state=(uint16_t)i[2];if((buttons&mask)!=(state&mask))return 0;o[0]=(int16_t)(clicks?1u:0u);o[1]=x;o[2]=y;o[3]=(int16_t)buttons;o[4]=(int16_t)kstate;return 0;}
static int32_t emouse(struct amtari_context*c,const int16_t*i,uint16_t ni,int16_t*o,uint16_t cap,uint16_t*n){int16_t x=0,y=0;uint16_t buttons=0,kstate=0;int ready,inside,leave;if(!i||ni<5||!o||cap<5)return AMTARI_EINVAL;memset(o,0,5*sizeof(*o));*n=5;if(!c->aes.mouse)return AMTARI_ENOSYS;ready=c->aes.mouse(c->aes.mouse_opaque,&x,&y,&buttons,&kstate);if(ready<=0)return 0;inside=point_in_rect(x,y,i[1],i[2],i[3],i[4]);leave=i[0]!=0;if((!leave&&inside)||(leave&&!inside)){o[0]=1;o[1]=x;o[2]=y;o[3]=(int16_t)buttons;o[4]=(int16_t)kstate;}return 0;}
static int32_t wupdate(const int16_t*i,uint16_t ni,int16_t*o,uint16_t cap,uint16_t*n){if(!i||ni<1||!o||cap<1)return AMTARI_EINVAL;o[0]=(int16_t)((i[0]==0||i[0]==1)?1:0);*n=1;return 0;}
static int32_t wfind(struct amtari_context*c,const int16_t*i,uint16_t ni,int16_t*o,uint16_t cap,uint16_t*n){int h;if(!i||ni<2||!o||cap<1)return AMTARI_EINVAL;o[0]=0;for(h=AMTARI_AES_WINDOW_MAX-1;h>0;h--){struct amtari_aes_window*w=&c->aes.windows[h];if(w->allocated&&w->open&&i[0]>=w->x&&i[1]>=w->y&&i[0]<w->x+w->w&&i[1]<w->y+w->h){o[0]=(int16_t)h;break;}}*n=1;return 0;}
static int32_t wset(struct amtari_context*c,const int16_t*i,uint16_t ni,int16_t*o,uint16_t cap,uint16_t*n){uint16_t h,field;if(!i||ni<2||!o||cap<1)return AMTARI_EINVAL;h=(uint16_t)i[0];field=(uint16_t)i[1];o[0]=(int16_t)(h>0&&h<AMTARI_AES_WINDOW_MAX&&c->aes.windows[h].allocated);*n=1;if(!o[0])return 0;if((field==4||field==5)&&ni<6)return AMTARI_EINVAL;if(field==5){c->aes.windows[h].x=i[2];c->aes.windows[h].y=i[3];c->aes.windows[h].w=i[4];c->aes.windows[h].h=i[5];}return 0;}
static int32_t wget(struct amtari_context*c,const int16_t*i,uint16_t ni,int16_t*o,uint16_t cap,uint16_t*n){uint16_t h,field;if(!i||ni<2||!o||cap<5)return AMTARI_EINVAL;h=(uint16_t)i[0];field=(uint16_t)i[1];o[0]=(int16_t)(h>0&&h<AMTARI_AES_WINDOW_MAX&&c->aes.windows[h].allocated);o[1]=o[2]=o[3]=o[4]=0;*n=5;if(!o[0])return 0;if(field==4||field==5){o[1]=c->aes.windows[h].x;o[2]=c->aes.windows[h].y;o[3]=c->aes.windows[h].w;o[4]=c->aes.windows[h].h;}return 0;}
static int32_t wdelete(struct amtari_context*c,const int16_t*i,uint16_t ni,int16_t*o,uint16_t cap,uint16_t*n){uint16_t h;if(!i||ni<1||!o||cap<1)return AMTARI_EINVAL;h=(uint16_t)i[0];o[0]=(int16_t)(h>0&&h<AMTARI_AES_WINDOW_MAX&&c->aes.windows[h].allocated);if(o[0]){c->aes.windows[h].allocated=0;c->aes.windows[h].open=0;}*n=1;return 0;}
static int32_t wclose(struct amtari_context*c,const int16_t*i,uint16_t ni,int16_t*o,uint16_t cap,uint16_t*n){uint16_t h;if(!i||ni<1||!o||cap<1)return AMTARI_EINVAL;h=(uint16_t)i[0];o[0]=(int16_t)(h>0&&h<AMTARI_AES_WINDOW_MAX&&c->aes.windows[h].allocated&&c->aes.windows[h].open);if(o[0])c->aes.windows[h].open=0;*n=1;return 0;}
static int32_t wopen(struct amtari_context*c,const int16_t*i,uint16_t ni,int16_t*o,uint16_t cap,uint16_t*n){uint16_t h;if(!i||ni<5||!o||cap<1)return AMTARI_EINVAL;h=(uint16_t)i[0];o[0]=(int16_t)(h>0&&h<AMTARI_AES_WINDOW_MAX&&c->aes.windows[h].allocated);if(o[0]){c->aes.windows[h].x=i[1];c->aes.windows[h].y=i[2];c->aes.windows[h].w=i[3];c->aes.windows[h].h=i[4];c->aes.windows[h].open=1;}*n=1;return 0;}
static int32_t wcreate(struct amtari_context*c,const int16_t*i,uint16_t ni,int16_t*o,uint16_t cap,uint16_t*n){uint16_t h;if(!i||ni<5||!o||cap<1)return AMTARI_EINVAL;for(h=1;h<AMTARI_AES_WINDOW_MAX;h++)if(!c->aes.windows[h].allocated)break;if(h==AMTARI_AES_WINDOW_MAX){o[0]=-1;*n=1;return 0;}c->aes.windows[h].allocated=1;c->aes.windows[h].open=0;c->aes.windows[h].x=i[1];c->aes.windows[h].y=i[2];c->aes.windows[h].w=i[3];c->aes.windows[h].h=i[4];if(h>=c->aes.next_window_handle)c->aes.next_window_handle=h+1;o[0]=(int16_t)h;*n=1;return 0;}
static int32_t fselexinput(const int16_t*i,uint16_t ni,const uint32_t*a,uint16_t na,int16_t*o,uint16_t cap,uint16_t*n){if(!i||ni<1||!a||na<3||!a[0]||!a[1]||!a[2]||!o||cap<1)return AMTARI_EINVAL;o[0]=1;*n=1;return 0;}
static int32_t fselinput(const int16_t*i,uint16_t ni,const uint32_t*a,uint16_t na,int16_t*o,uint16_t cap,uint16_t*n){if(!i||ni<1||!a||na<1||!a[0]||!o||cap<1)return AMTARI_EINVAL;o[0]=1;*n=1;return 0;}
static int32_t swrite(struct amtari_context*c,const uint32_t*a,uint16_t na,int16_t*o,uint16_t cap,uint16_t*n){uint32_t q;size_t k=0;if(!a||na<1||!a[0]||!o||cap<1)return AMTARI_EINVAL;q=a[0];while(k<AMTARI_SCRAP_PATH_MAX-1u){if(!amtari_guest_range_valid(c,q+k,1))return AMTARI_EFAULT;c->aes.scrap_path[k]=(char)c->memory.data[q+k];if(!c->aes.scrap_path[k])break;k++;}if(k==AMTARI_SCRAP_PATH_MAX-1u)c->aes.scrap_path[k]=0;o[0]=1;*n=1;return 0;}
static int32_t sread(struct amtari_context*c,const uint32_t*a,uint16_t na,int16_t*o,uint16_t cap,uint16_t*n){uint32_t q;size_t len;if(!a||na<1||!a[0]||!o||cap<1)return AMTARI_EINVAL;q=a[0];len=strlen(c->aes.scrap_path)+1u;if(!amtari_guest_range_valid(c,q,len))return AMTARI_EFAULT;memcpy(c->memory.data+q,c->aes.scrap_path,len);o[0]=1;*n=1;return 0;}
static int32_t gslidebox(const int16_t*i,uint16_t ni,const uint32_t*a,uint16_t na,int16_t*o,uint16_t cap,uint16_t*n){if(!i||ni<3||!a||na<1||!a[0]||!o||cap<1)return AMTARI_EINVAL;o[0]=0;*n=1;return 0;}
static int32_t gwatchbox(struct amtari_context*c,const int16_t*i,uint16_t ni,const uint32_t*a,uint16_t na,int16_t*o,uint16_t cap,uint16_t*n){int16_t x=0,y=0;uint16_t buttons=0,kstate=0;int ready;if(!i||ni<3||!a||na<1||!a[0]||!o||cap<1)return AMTARI_EINVAL;o[0]=0;*n=1;if(!c->aes.mouse)return AMTARI_ENOSYS;ready=c->aes.mouse(c->aes.mouse_opaque,&x,&y,&buttons,&kstate);if(ready<0)return AMTARI_EIO;if(!ready)return 0;o[0]=(int16_t)(buttons?1:0);return 0;}
static int32_t gshrinkbox(const int16_t*i,uint16_t ni,int16_t*o,uint16_t cap,uint16_t*n){if(!i||ni<8||!o||cap<1)return AMTARI_EINVAL;o[0]=1;*n=1;return 0;}
static int32_t ggrowbox(const int16_t*i,uint16_t ni,int16_t*o,uint16_t cap,uint16_t*n){if(!i||ni<8||!o||cap<1)return AMTARI_EINVAL;o[0]=1;*n=1;return 0;}
static int32_t gmovebox(const int16_t*i,uint16_t ni,int16_t*o,uint16_t cap,uint16_t*n){if(!i||ni<6||!o||cap<1)return AMTARI_EINVAL;o[0]=1;*n=1;return 0;}
static int32_t gdragbox(struct amtari_context*c,const int16_t*i,uint16_t ni,int16_t*o,uint16_t cap,uint16_t*n){int16_t mx=0,my=0;uint16_t buttons=0,kstate=0;int ready;int32_t x,y,maxx,maxy;if(!i||ni<8||!o||cap<3)return AMTARI_EINVAL;o[0]=o[1]=o[2]=0;*n=3;if(!c->aes.mouse)return AMTARI_ENOSYS;ready=c->aes.mouse(c->aes.mouse_opaque,&mx,&my,&buttons,&kstate);if(ready<0)return AMTARI_EIO;if(!ready)return 0;x=mx;y=my;maxx=(int32_t)i[4]+(int32_t)i[6]-(int32_t)i[0];maxy=(int32_t)i[5]+(int32_t)i[7]-(int32_t)i[1];if(maxx<i[4])maxx=i[4];if(maxy<i[5])maxy=i[5];if(x<i[4])x=i[4];if(y<i[5])y=i[5];if(x>maxx)x=maxx;if(y>maxy)y=maxy;o[0]=1;o[1]=(int16_t)x;o[2]=(int16_t)y;return 0;}
static int32_t grubbox(struct amtari_context*c,const int16_t*i,uint16_t ni,int16_t*o,uint16_t cap,uint16_t*n){int16_t x=0,y=0;uint16_t buttons=0,kstate=0;int ready;int32_t w,h,minw,minh;if(!i||ni<4||!o||cap<3)return AMTARI_EINVAL;o[0]=o[1]=o[2]=0;*n=3;if(!c->aes.mouse)return AMTARI_ENOSYS;ready=c->aes.mouse(c->aes.mouse_opaque,&x,&y,&buttons,&kstate);if(ready<0)return AMTARI_EIO;if(!ready)return 0;w=(int32_t)x-(int32_t)i[0]+1;h=(int32_t)y-(int32_t)i[1]+1;minw=i[2];minh=i[3];if(minw>=0&&w<minw)w=minw;if(minw<0&&w>minw)w=minw;if(minh>=0&&h<minh)h=minh;if(minh<0&&h>minh)h=minh;o[0]=1;o[1]=(int16_t)w;o[2]=(int16_t)h;return 0;}
static int32_t ghandle(struct amtari_context*c,int16_t*o,uint16_t cap,uint16_t*n){if(!o||cap<5)return AMTARI_EINVAL;o[0]=(int16_t)c->aes.workstation_handle;o[1]=(int16_t)c->aes.char_width;o[2]=(int16_t)c->aes.char_height;o[3]=(int16_t)c->aes.box_width;o[4]=(int16_t)c->aes.box_height;*n=5;return 0;}
static int32_t gmouse(struct amtari_context*c,const int16_t*i,uint16_t ni,const uint32_t*a,uint16_t na,int16_t*o,uint16_t cap,uint16_t*n){uint16_t mode;uint32_t form=0;if(!i||ni<1||!o||cap<1)return AMTARI_EINVAL;mode=(uint16_t)i[0];if(a&&na)form=a[0];o[0]=0;*n=1;if(mode==255u&&(!a||na<1||!form))return AMTARI_EINVAL;if(!c->aes.cursor)return AMTARI_ENOSYS;if(c->aes.cursor(c->aes.cursor_opaque,mode,form))return AMTARI_EIO;o[0]=1;return 0;}
static int32_t gmkstate(struct amtari_context*c,int16_t*o,uint16_t cap,uint16_t*n){int16_t x=0,y=0;uint16_t buttons=0,kstate=0;int ready;if(!o||cap<5)return AMTARI_EINVAL;memset(o,0,5*sizeof(*o));*n=5;if(!c->aes.mouse)return AMTARI_ENOSYS;ready=c->aes.mouse(c->aes.mouse_opaque,&x,&y,&buttons,&kstate);if(ready<0)return AMTARI_EIO;o[0]=1;o[1]=x;o[2]=y;o[3]=(int16_t)buttons;o[4]=(int16_t)kstate;return 0;}
static int32_t emulti(struct amtari_context*c,const int16_t*i,uint16_t ni,const uint32_t*a,uint16_t na,int16_t*o,uint16_t cap,uint16_t*n){uint16_t flags,events=0,buttons=0,kstate=0;int16_t mx=0,my=0;uint32_t ms,q=0;int key,mouse_sampled=0,mouse_ready=0;if(!i||ni<16||!o||cap<7)return AMTARI_EINVAL;flags=(uint16_t)i[0];memset(o,0,7*sizeof(*o));*n=7;if((flags&MU_MESAG)&&c->aes.application_active&&c->aes.message_pending&&c->aes.message_destination==c->aes.current_application_id&&c->aes.message_length==16){if(!a||na<1)return AMTARI_EINVAL;q=a[0];if(!amtari_guest_range_valid(c,q,16))return AMTARI_EFAULT;memcpy(c->memory.data+q,c->aes.message,16);c->aes.message_pending=0;c->aes.message_length=0;c->aes.message_destination=0;events|=MU_MESAG;}if((flags&MU_KEYBD)&&c->console.input_ready&&c->console.getc&&c->console.input_ready(c->console.opaque)>0){key=c->console.getc(c->console.opaque);if(key>=0){o[5]=(int16_t)(uint16_t)key;events|=MU_KEYBD;}}if((flags&(MU_BUTTON|MU_M1|MU_M2))&&c->aes.mouse){mouse_sampled=1;mouse_ready=c->aes.mouse(c->aes.mouse_opaque,&mx,&my,&buttons,&kstate);if(mouse_ready>0){o[1]=mx;o[2]=my;o[3]=(int16_t)buttons;o[4]=(int16_t)kstate;}}if((flags&MU_BUTTON)&&mouse_sampled&&mouse_ready>0){uint16_t clicks=(uint16_t)i[1],mask=(uint16_t)i[2],state=(uint16_t)i[3];(void)clicks;if((buttons&mask)==(state&mask)){o[6]=1;events|=MU_BUTTON;}}if((flags&MU_M1)&&mouse_sampled&&mouse_ready>0){int inside=point_in_rect(mx,my,i[5],i[6],i[7],i[8]);int leave=i[4]!=0;if((!leave&&inside)||(leave&&!inside))events|=MU_M1;}if((flags&MU_M2)&&mouse_sampled&&mouse_ready>0){int inside=point_in_rect(mx,my,i[10],i[11],i[12],i[13]);int leave=i[9]!=0;if((!leave&&inside)||(leave&&!inside))events|=MU_M2;}if((flags&MU_TIMER)&&!events){ms=(uint32_t)(uint16_t)i[14]|((uint32_t)(uint16_t)i[15]<<16);c->aes.last_timer_ms=ms;if(c->aes.timer&&c->aes.timer(c->aes.timer_opaque,ms))return AMTARI_EIO;events|=MU_TIMER;}o[0]=(int16_t)events;return 0;}
int32_t amtari_aes_dispatch(struct amtari_context*c,uint16_t op,const int16_t*i,uint16_t ni,int16_t*o,uint16_t oc,uint16_t*no,const uint32_t*a,uint16_t na,uint32_t*ao,uint16_t aoc,uint16_t*nao){int32_t r;if(!c||!c->initialized||!no||!nao)return AMTARI_EINVAL;*no=*nao=0;if(op==10)return ainit(c,o,oc,no);if(op==11)return aread(c,i,ni,a,na,o,oc,no);if(op==12)return awrite(c,i,ni,a,na,o,oc,no);if(op==13)return afind(c,a,na,o,oc,no);if(op==19)return aexit(c,o,oc,no);if(op==20)return ekeybd(c,o,oc,no);if(op==21)return ebutton(c,i,ni,o,oc,no);if(op==22)return emouse(c,i,ni,o,oc,no);if(op==23)return emesag(c,a,na,o,oc,no);if(op==24)return etimer(c,i,ni,o,oc,no);if(op==25)return emulti(c,i,ni,a,na,o,oc,no);if(op==70)return grubbox(c,i,ni,o,oc,no);if(op==71)return gdragbox(c,i,ni,o,oc,no);if(op==72)return gmovebox(i,ni,o,oc,no);if(op==73)return ggrowbox(i,ni,o,oc,no);if(op==74)return gshrinkbox(i,ni,o,oc,no);if(op==75)return gwatchbox(c,i,ni,a,na,o,oc,no);if(op==76)return gslidebox(i,ni,a,na,o,oc,no);if(op==77)return ghandle(c,o,oc,no);if(op==78)return gmouse(c,i,ni,a,na,o,oc,no);if(op==79)return gmkstate(c,o,oc,no);if(op==80)return sread(c,a,na,o,oc,no);if(op==81)return swrite(c,a,na,o,oc,no);if(op==90)return fselinput(i,ni,a,na,o,oc,no);if(op==91)return fselexinput(i,ni,a,na,o,oc,no);if(op==100)return wcreate(c,i,ni,o,oc,no);if(op==101)return wopen(c,i,ni,o,oc,no);if(op==102)return wclose(c,i,ni,o,oc,no);if(op==103)return wdelete(c,i,ni,o,oc,no);if(op==104)return wget(c,i,ni,o,oc,no);if(op==105)return wset(c,i,ni,o,oc,no);if(op==106)return wfind(c,i,ni,o,oc,no);if(op==107)return wupdate(i,ni,o,oc,no);if(!c->aes.dispatch)return AMTARI_ENOSYS;r=c->aes.dispatch(c->aes.opaque,op,i,ni,o,oc,no,a,na,ao,aoc,nao);if(r)return r;if(*no>oc||*nao>aoc)return AMTARI_EINVAL;return 0;}
