#include "amtari.h"
#include <string.h>
#define MU_MESAG 0x0010u
#define MU_TIMER 0x0020u
int amtari_vdi_bind(struct amtari_context *c,amtari_vdi_dispatch_fn f,void*o){if(!c||!c->initialized)return AMTARI_EINVAL;c->vdi.dispatch=f;c->vdi.opaque=o;return 0;}int amtari_vdi_line_bind(struct amtari_context*c,amtari_vdi_line_fn f,void*o){if(!c||!c->initialized)return AMTARI_EINVAL;c->vdi.line=f;c->vdi.line_opaque=o;return 0;}int amtari_vdi_configure(struct amtari_context*c,uint16_t w,uint16_t h,uint16_t n){if(!c||!c->initialized||!w||!h||!n)return AMTARI_EINVAL;c->vdi.width=w;c->vdi.height=h;c->vdi.colors=n;if(!c->vdi.next_handle)c->vdi.next_handle=1;if(!c->vdi.line_style)c->vdi.line_style=1;return 0;}
static int32_t opnwk(struct amtari_context*c,int16_t*o,uint16_t oc,uint16_t*no,int16_t*p,uint16_t pc,uint16_t*np){uint16_t i;if(!c->vdi.width||!c->vdi.height||!c->vdi.colors)return AMTARI_ENOSYS;if(oc<45||pc<12||!o||!p)return AMTARI_EINVAL;for(i=0;i<45;i++)o[i]=0;for(i=0;i<12;i++)p[i]=0;o[0]=(int16_t)(c->vdi.width-1);o[1]=(int16_t)(c->vdi.height-1);o[3]=o[4]=o[5]=o[6]=o[7]=o[8]=o[9]=o[10]=1;o[13]=(int16_t)c->vdi.colors;o[35]=1;*no=45;*np=12;c->vdi.next_handle++;return 0;}static int32_t attr(struct amtari_context*c,uint16_t op,const int16_t*i,uint16_t n,int16_t*o,uint16_t cap,uint16_t*cnt){uint16_t v;if(!i||n<1||!o||cap<1)return AMTARI_EINVAL;v=(uint16_t)i[0];if(op==15){if(v<1||v>6)v=1;c->vdi.line_style=v;}else{if(v>=c->vdi.colors)v=1;c->vdi.line_color=v;}o[0]=(int16_t)v;*cnt=1;return 0;}static int32_t pline(struct amtari_context*c,const int16_t*p,uint16_t n){uint16_t i;if(!c->vdi.line)return AMTARI_ENOSYS;if(!p||n<4||(n&1))return AMTARI_EINVAL;for(i=0;i+3<n;i+=2)if(c->vdi.line(c->vdi.line_opaque,p[i],p[i+1],p[i+2],p[i+3],c->vdi.line_color,c->vdi.line_style))return AMTARI_EIO;return 0;}
int32_t amtari_vdi_dispatch(struct amtari_context*c,uint16_t op,const int16_t*i,uint16_t ni,const int16_t*p,uint16_t np,int16_t*o,uint16_t oc,uint16_t*no,int16_t*po,uint16_t pc,uint16_t*npo){int32_t r;if(!c||!c->initialized||!no||!npo)return AMTARI_EINVAL;*no=*npo=0;if(op==1)return opnwk(c,o,oc,no,po,pc,npo);if(op==6)return pline(c,p,np);if(op==15||op==17)return attr(c,op,i,ni,o,oc,no);if(!c->vdi.dispatch)return AMTARI_ENOSYS;r=c->vdi.dispatch(c->vdi.opaque,op,i,ni,p,np,o,oc,no,po,pc,npo);if(r)return r;if(*no>oc||*npo>pc)return AMTARI_EINVAL;return 0;}
int amtari_aes_bind(struct amtari_context*c,amtari_aes_dispatch_fn f,void*o){if(!c||!c->initialized)return AMTARI_EINVAL;c->aes.dispatch=f;c->aes.opaque=o;return 0;}int amtari_aes_timer_bind(struct amtari_context*c,amtari_aes_timer_fn f,void*o){if(!c||!c->initialized)return AMTARI_EINVAL;c->aes.timer=f;c->aes.timer_opaque=o;return 0;}int amtari_aes_set_application_name(struct amtari_context*c,const char*n){size_t z;if(!c||!c->initialized||!n)return AMTARI_EINVAL;z=strlen(n);if(!z||z>8)return AMTARI_EINVAL;memset(c->aes.application_name,0,9);memcpy(c->aes.application_name,n,z);return 0;}
static int32_t ainit(struct amtari_context*c,int16_t*o,uint16_t cap,uint16_t*n){uint16_t id;if(!o||cap<1)return AMTARI_EINVAL;if(c->aes.application_active)return AMTARI_EEXIST;if(!c->aes.next_application_id)c->aes.next_application_id=1;id=c->aes.next_application_id++;c->aes.current_application_id=id;c->aes.application_active=1;o[0]=(int16_t)id;*n=1;return 0;}static int32_t aexit(struct amtari_context*c,int16_t*o,uint16_t cap,uint16_t*n){if(!o||cap<1||!c->aes.application_active)return AMTARI_EINVAL;c->aes.application_active=0;c->aes.current_application_id=0;c->aes.message_pending=0;c->aes.message_length=0;o[0]=1;*n=1;return 0;}static int32_t afind(struct amtari_context*c,const uint32_t*a,uint16_t na,int16_t*o,uint16_t cap,uint16_t*n){char s[9];uint16_t i;uint32_t q;if(!o||cap<1||!a||na<1)return AMTARI_EINVAL;o[0]=-1;*n=1;if(!c->aes.application_active||!c->aes.application_name[0])return 0;q=a[0];for(i=0;i<8;i++){if(!amtari_guest_range_valid(c,q+i,1))return AMTARI_EFAULT;s[i]=(char)c->memory.data[q+i];if(!s[i])break;}if(i==8)s[8]=0;else s[i]=0;if(!strcmp(s,c->aes.application_name))o[0]=(int16_t)c->aes.current_application_id;return 0;}
static int32_t awrite(struct amtari_context*c,const int16_t*i,uint16_t ni,const uint32_t*a,uint16_t na,int16_t*o,uint16_t cap,uint16_t*n){uint16_t dest,len;uint32_t q;if(!o||cap<1||!i||ni<2||!a||na<1)return AMTARI_EINVAL;dest=(uint16_t)i[0];len=(uint16_t)i[1];q=a[0];o[0]=0;*n=1;if(!c->aes.application_active||dest!=c->aes.current_application_id||len>AMTARI_AES_MESSAGE_MAX||c->aes.message_pending)return 0;if(!amtari_guest_range_valid(c,q,len))return AMTARI_EFAULT;if(len)memcpy(c->aes.message,c->memory.data+q,len);c->aes.message_length=len;c->aes.message_destination=dest;c->aes.message_pending=1;o[0]=1;return 0;}
static int32_t aread(struct amtari_context*c,const int16_t*i,uint16_t ni,const uint32_t*a,uint16_t na,int16_t*o,uint16_t cap,uint16_t*n){uint16_t rid,len;uint32_t q;if(!o||cap<1||!i||ni<2||!a||na<1)return AMTARI_EINVAL;rid=(uint16_t)i[0];len=(uint16_t)i[1];q=a[0];o[0]=0;*n=1;if(!c->aes.application_active||rid!=c->aes.current_application_id||!c->aes.message_pending||c->aes.message_destination!=rid||len!=c->aes.message_length)return 0;if(!amtari_guest_range_valid(c,q,len))return AMTARI_EFAULT;if(len)memcpy(c->memory.data+q,c->aes.message,len);c->aes.message_pending=0;c->aes.message_length=0;c->aes.message_destination=0;o[0]=1;return 0;}
static int32_t emesag(struct amtari_context*c,const uint32_t*a,uint16_t na,int16_t*o,uint16_t cap,uint16_t*n){uint32_t q;if(!o||cap<1||!a||na<1)return AMTARI_EINVAL;q=a[0];o[0]=0;*n=1;if(!c->aes.application_active||!c->aes.message_pending||c->aes.message_destination!=c->aes.current_application_id||c->aes.message_length!=16)return 0;if(!amtari_guest_range_valid(c,q,16))return AMTARI_EFAULT;memcpy(c->memory.data+q,c->aes.message,16);c->aes.message_pending=0;c->aes.message_length=0;c->aes.message_destination=0;o[0]=1;return 0;}
static int32_t etimer(struct amtari_context*c,const int16_t*i,uint16_t ni,int16_t*o,uint16_t cap,uint16_t*n){uint32_t ms;if(!o||cap<1||!i||ni<2)return AMTARI_EINVAL;ms=(uint32_t)(uint16_t)i[0]|((uint32_t)(uint16_t)i[1]<<16);c->aes.last_timer_ms=ms;if(c->aes.timer&&c->aes.timer(c->aes.timer_opaque,ms))return AMTARI_EIO;o[0]=1;*n=1;return 0;}
static int32_t emulti(struct amtari_context*c,const int16_t*i,uint16_t ni,const uint32_t*a,uint16_t na,int16_t*o,uint16_t cap,uint16_t*n){uint16_t flags,events=0;uint32_t ms,q=0;if(!i||ni<16||!o||cap<7)return AMTARI_EINVAL;flags=(uint16_t)i[0];memset(o,0,7*sizeof(*o));*n=7;if((flags&MU_MESAG)&&c->aes.application_active&&c->aes.message_pending&&c->aes.message_destination==c->aes.current_application_id&&c->aes.message_length==16){if(!a||na<1)return AMTARI_EINVAL;q=a[0];if(!amtari_guest_range_valid(c,q,16))return AMTARI_EFAULT;memcpy(c->memory.data+q,c->aes.message,16);c->aes.message_pending=0;c->aes.message_length=0;c->aes.message_destination=0;events|=MU_MESAG;}if((flags&MU_TIMER)&&!events){ms=(uint32_t)(uint16_t)i[14]|((uint32_t)(uint16_t)i[15]<<16);c->aes.last_timer_ms=ms;if(c->aes.timer&&c->aes.timer(c->aes.timer_opaque,ms))return AMTARI_EIO;events|=MU_TIMER;}o[0]=(int16_t)events;return 0;}
int32_t amtari_aes_dispatch(struct amtari_context*c,uint16_t op,const int16_t*i,uint16_t ni,int16_t*o,uint16_t oc,uint16_t*no,const uint32_t*a,uint16_t na,uint32_t*ao,uint16_t aoc,uint16_t*nao){int32_t r;if(!c||!c->initialized||!no||!nao)return AMTARI_EINVAL;*no=*nao=0;if(op==10)return ainit(c,o,oc,no);if(op==11)return aread(c,i,ni,a,na,o,oc,no);if(op==12)return awrite(c,i,ni,a,na,o,oc,no);if(op==13)return afind(c,a,na,o,oc,no);if(op==19)return aexit(c,o,oc,no);if(op==23)return emesag(c,a,na,o,oc,no);if(op==24)return etimer(c,i,ni,o,oc,no);if(op==25)return emulti(c,i,ni,a,na,o,oc,no);if(!c->aes.dispatch)return AMTARI_ENOSYS;r=c->aes.dispatch(c->aes.opaque,op,i,ni,o,oc,no,a,na,ao,aoc,nao);if(r)return r;if(*no>oc||*nao>aoc)return AMTARI_EINVAL;return 0;}
